### PR TITLE
teardown heatmap webpage of the "smashing magazine"

### PR DESCRIPTION
**Pull request by andresporras3423**

### CODE REVIEW

**Comment by andresporras3423** [comment]
- use of flexbox, CSS Grid, and float for the layout
- use of article tag
- HTML semantic tags
- use of google fonts and font sizes

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @andresporras3423 and @abdelp 

### Good job guys so far, however, there are issues you need to work on. In terms of visual hierarchy, typography and design principles which the project is testing. You need to do better than this.
- Use icons
- Use colors
- Typography make it better
- add spaces where necessary
- You can use images as well
- give your project a feel

### Once you have made all these changes, resubmit your project for review. I wish you the best in the next submission. Happy coding!
You can always reach out for help and more so always reference the original website [smashing magazine](https://www.smashingmagazine.com/)

**Comment by andresporras3423** [comment]
Hi rOluochKe,

According to the instructions, we should create a grayscale heatmap of the website, that's why we didn't use icons, images or colors, that's why our page is not a clone of the smashing page  This is the link to this project:

https://www.theodinproject.com/courses/html5-and-css3/lessons/design-teardown

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi Team, you have done a great job so far. Kindly fix the error below:
- ``` LINE 183 ``` display:hide is not a display value. Check errors [here](https://jigsaw.w3.org/css-validator)
css

In your next project remember to give your pull request a title and short summary
pr

Kindly fix this and submit another code review. :+1: 
Happy coding :computer:

**Comment by andresporras3423** [comment]
fixed 'display: hide' with 'display: none;'

**Review by addod19 — APPROVED** [review]
## Status: Approved :airplane: 

**Hi Team**, congratulations on a job well done. You have met all the minimum requirement. :+1: 
You can now merge to master and submit project completion form :slightly_smiling_face: 

Good luck with your next project. 
Happy coding :computer:

**Comment by andresporras3423** [comment]
thanks

**Pull request merged**
